// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

import { beforeEach, describe, expect, it, jest } from '@jest/globals';

jest.unstable_mockModule('../../src/lib/mcp-handlers/github-request.js', () => ({
  githubRequest: jest.fn(),
}));

const { githubRequest } = await import('../../src/lib/mcp-handlers/github-request.js');
const { createDraftPr } = await import('../../src/lib/mcp-handlers/create-draft-pr.js');

describe('createDraftPr', () => {
  beforeEach(() => {
    githubRequest.mockReset();
  });

  it('creates a draft PR and returns prNumber and prUrl', async () => {
    githubRequest.mockResolvedValueOnce({
      status: 201,
      data: {
        number: 88,
        html_url: 'https://github.com/org/repo/pull/88',
      },
    });

    const result = await createDraftPr({
      owner: 'org',
      repo: 'repo',
      branch: 'agent/ai-42',
      baseBranch: 'main',
      title: 'Fix: implement feature X',
      body: 'This PR implements feature X.',
      issueNumber: 42,
    });

    expect(result).toEqual({
      prNumber: 88,
      prUrl: 'https://github.com/org/repo/pull/88',
    });

    expect(githubRequest).toHaveBeenCalledTimes(1);
    const [owner, repo, method, path, body] = githubRequest.mock.calls[0];
    expect(owner).toBe('org');
    expect(repo).toBe('repo');
    expect(method).toBe('POST');
    expect(path).toBe('/repos/org/repo/pulls');
    expect(body.title).toBe('Fix: implement feature X');
    expect(body.head).toBe('agent/ai-42');
    expect(body.base).toBe('main');
    expect(body.draft).toBe(true);
  });

  it('appends Closes #N footer to the PR body', async () => {
    githubRequest.mockResolvedValueOnce({
      status: 201,
      data: { number: 99, html_url: 'https://github.com/org/repo/pull/99' },
    });

    await createDraftPr({
      owner: 'org',
      repo: 'repo',
      branch: 'agent/ai-7',
      baseBranch: 'main',
      title: 'Some PR',
      body: 'Original body text.',
      issueNumber: 7,
    });

    const [, , , , body] = githubRequest.mock.calls[0];
    expect(body.body).toContain('Original body text.');
    expect(body.body).toContain('Closes #7');
    expect(body.body).toContain('Generated by Fiona coding agent');
  });
});
